name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy Files to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/html" # Remote server path

    - name: SSH into Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html
          sudo chown -R www-data:www-data /var/www/html
          sudo systemctl restart nginx

# name: Deploy to Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Set server IP
#       run: echo "SERVER_IP=${{ secrets.SERVER_IP }}" >> $GITHUB_ENV

#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Install rsync
#       run: sudo apt update && sudo apt install rsync -y

#     - name: Deploy to Server
#       run: |
#         rsync -avz --delete ./ user@$SERVER_IP:/var/www/html/
#         ssh user@$SERVER_IP 'sudo chown -R www-data:www-data /var/www/html/wordpress'
#         ssh user@$SERVER_IP 'sudo systemctl restart nginx'
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

